### ISSUE TITLE
Config file conflicts when multiple instances are running

### ISSUE THREAD

**Issue by olepoeschl** [olepoeschl/NQueensFAF-GUI#120]

**Comment by timmitohnetim** [comment]
Können wir da nicht einfach für jedes Gerät einen eigenen Abschnitt in das
config file einfügen?

**Comment by olepoeschl** [comment]
Gute idee!
Dann müssen wir allerdings trotzdem noch was machen, damit man nicht bei
allen instanzen das gleiche Gerät auswählen und dann an den gleichen
configs rumdrehen kann. Vllt mit nem file als mutex, ich google aber
nochmal ob das auch anders geht

**Comment by olepoeschl** [comment]
Superceded by #123
